colors: true

prepare-commit-msg:
  commands:
    commitlint:
      run: pnpm commitlint --edit $1

pre-commit:
  parallel: true
  commands:
    prettier:
      glob: '*.{js,ts,jsx,tsx,astro,md}'
      run: pnpm format {staged_files} && git update-index --again
      stage_fixed: true
    eslint:
      glob: '*.{js,ts,jsx,tsx,astro,md}'
      run: pnpm lint:fix {staged_files} && git update-index --again
      stage_fixed: true
    test:
      run: pnpm test:ci {staged_files} && git update-index --again

pre-push:
  parallel: true
  commands:
    typescript:
      run: pnpm typecheck
    build:
      run: pnpm build
#    packages-audit:
#      tags: frontend security
#      run: pnpm audit
